version: '{build}'
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- ps: |
    $ErrorActionPreference="Stop"

    appveyor-retry cinst 7zip.commandline -y
    appveyor-retry cinst unity -y
    appveyor-retry cinst putty -y
    appveyor-retry cinst winscp -y

    Write-Host "Saving RSA key for SCP"
    $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
    $fileContent += $env:SSH_PRIVATE_KEY.Replace(' ', "`n")
    $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
    Set-Content c:\users\appveyor\.ssh\id_rsa_scp $fileContent

    Write-Host "Converting PEM to PPK using WinSCP"
    Start-Process "C:\Program Files (x86)\WinSCP\WinSCP.com" -ArgumentList "/keygen c:\users\appveyor\.ssh\id_rsa_scp /output=c:\users\appveyor\.ssh\id_rsa_scp.ppk"

    $ErrorActionPreference="SilentlyContinue"

    Write-Host "Loading CACerts for Unity via PSCP"
    $source = $env:SCP_SOURCE
    $source += "/CACerts.pem"
    $target = "C:\users\appveyor\AppData\Roaming\Unity\Certificates\CACerts.pem"
    mkdir -Force C:\users\appveyor\AppData\Roaming\Unity\Certificates\
    echo "Y`r" | C:\ProgramData\chocolatey\lib\putty.portable\tools\PSCP.EXE -i "c:\users\appveyor\.ssh\id_rsa_scp.ppk" $source $target

    Write-Host "Loading Unity_lic.ulf for Unity via PSCP"
    $source = $env:SCP_SOURCE
    $source += "/Unity_lic.ulf"
    $target = "C:\ProgramData\Unity\Unity_lic.ulf"
    mkdir -Force C:\ProgramData\Unity\
    echo "Y`r" | C:\ProgramData\chocolatey\lib\putty.portable\tools\PSCP.EXE -i "c:\users\appveyor\.ssh\id_rsa_scp.ppk" $source $target

    Write-Host Start-Process "C:\Program Files\Unity\Editor\Unity.exe" -ArgumentList "-quit -batchmode -nographics -logfile log.txt -username `"***`" -password `"***`"" -NoNewWindow -Wait
    Start-Process "C:\Program Files\Unity\Editor\Unity.exe" -ArgumentList "-quit -batchmode -nographics -logfile log.txt -username `"$env:UNITY_USER`" -password `"$env:UNITY_PASS`"" -NoNewWindow -Wait
    cat log.txt

build_script:
- ps: |
    $ErrorActionPreference="Stop"
    
    mkdir -Force $env:APPVEYOR_BUILD_FOLDER\work\build\$env:APPVEYOR_PROJECT_NAME
    cd $env:APPVEYOR_BUILD_FOLDER\work\build\$env:APPVEYOR_PROJECT_NAME

    $ARTIFACT_FOLDER = $env:PLATFORM;
    Switch ($env:PLATFORM)
    {
        Win64 {
            $UNITY_TARGET = "buildWindows64Player"
            $TARGET_FILE = "Win64\\stalnias.exe"
        }
        WebGL {
            $UNITY_TARGET = "buildWebPlayer"
            $TARGET_FILE = "WebGL\\"
        }
    }

    Write-Host Start-Process "C:\Program Files\Unity\Editor\Unity.exe" -ArgumentList "-quit -batchmode -nographics -projectPath=$env:APPVEYOR_BUILD_FOLDER -$UNITY_TARGET $env:APPVEYOR_BUILD_FOLDER\work\build\$TARGET_FILE -logfile log.txt" -NoNewWindow -Wait
    Start-Process "C:\Program Files\Unity\Editor\Unity.exe" -ArgumentList "-quit -batchmode -nographics -projectPath=$env:APPVEYOR_BUILD_FOLDER -$UNITY_TARGET $env:APPVEYOR_BUILD_FOLDER\work\build\$TARGET_FILE -logfile log.txt" -NoNewWindow -Wait
    cat log.txt

    $commit = ([string]$env:APPVEYOR_REPO_COMMIT).SubString(0,6)
    $date = Get-Date -UFormat "%y.%m.%d"
    $imageName = "stalnias.a."+$date+"_"+$ARTIFACT_FOLDER+"_"+$commit
    
    Write-Host 7za a "$env:APPVEYOR_BUILD_FOLDER\work\deployImage\$imageName.7z" "$env:APPVEYOR_BUILD_FOLDER\work\build\$ARTIFACT_FOLDER\*"
    7za a "$env:APPVEYOR_BUILD_FOLDER\work\deployImage\$imageName.7z" "$env:APPVEYOR_BUILD_FOLDER\work\build\$ARTIFACT_FOLDER\*"
    Write-Host Push-AppveyorArtifact "$env:APPVEYOR_BUILD_FOLDER\work\deployImage\$imageName.7z"
    Push-AppveyorArtifact "$env:APPVEYOR_BUILD_FOLDER\work\deployImage\$imageName.7z"    

environment:
    matrix:
        - PLATFORM: Win64
        - PLATFORM: WebGL

test: off

cache:
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
    - C:\Program Files\Unity\ -> appveyor.yml
